(in-package :scsu)

(defun test-0 (char)
  (format t "~&Character ~C, code ~X~%" char (char-code char))
  (multiple-value-bind (buffer current)
      (encode-unit-to-buffer (char-code char))
    (format t "Buffer:~A, Current ~A~%" buffer current)
    (let* ((ret (decode-unit-to-buffer buffer))
	   (ret-char (code-char ret)))
      (format t "~&Restored code ~X, char ~C~%" ret ret-char)
      ret-char)))
